# -*- coding: utf-8 -*-
"""ob-havo_bashorati_dc_and_si

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_UvORpQnjAk53qLCuH7pPQisLDQlWBiR
"""

# Bu kod dastur orqali qanday iqlimda hosilimiz yaxshi, o'rtacha, yomon bo'lishini bilib olamiz

# Kerakli kutubxonani chaqiramiz
from sklearn import tree

# Model yaratamiz
clf = tree.DecisionTreeClassifier()

# Ma'lumotlar (xususiyatlar)
# Misol uchun birinchi qator (220-quyoshli, 110-yomg'irli, 35-qorli kun bo'lganda)
# [quyoshli_kunlar, yomg'irli_kunlar, qorli_kunlar]
x = [
    [220, 110, 35],
    [290, 60, 15],
    [260, 75, 30],
    [210, 140, 15],
    [200, 140, 25],
    [180, 180, 5],
    [180, 135, 50],
    [205, 120, 35],
    [110, 180, 75],
    [95, 197, 73]
]

# Biz belgilagan taxminiy natijalar (yorliqlar)
y = [
    'yaxshi',
    'yomon',
    "o'rtacha",
    'yaxshi',
    "o'rtacha",
    'yomon',
    'yaxshi',
    "o'rtacha",
    'yomon',
    'yomon'
]

# Modelni o‘rgatamiz yani bu orqali bashorat qilinadi
clf = clf.fit(x, y)

# Yangi ma'lumot uchun bashorat
taxmin = clf.predict([[95, 170, 100]])
taxmin2 = clf.predict([[100, 100, 65]])
taxmin3 = clf.predict([[115,65,15]])

# Natijani chiqaramiz
print(taxmin)
print(taxmin2)
print(taxmin3)